# Generated by Django 4.0.5 on 2022-06-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?f=y', max_length=255),
        ),
    ]
