# Generated by Django 4.0.5 on 2022-06-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
