# Generated by Django 4.0.5 on 2022-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
    ]
