# Generated by Django 4.0.5 on 2022-06-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0012_rating_content_average_rating_creativity_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creativity_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design_average',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability_average',
        ),
    ]
